[package]
name = "sticky_note"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sn"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
microkv = "0.2.9"
home = "0.5.4"
